### ISSUE TITLE
CSV data

### ISSUE THREAD

**Issue by p1m3nt** [bang-js/Taming_the_Factor_Zoo#2]
Could you please also post the data used in your notebook? Thanks

**Comment by bang-js** [comment]
I'm sorry for the delayed response. The data I used for replication is accessible at https://doi.org/10.1111/jofi.12883. The file name is jofi12883-sup-0001-ReplicationCode.zip (See the supporting information)

**Comment by p1m3nt** [comment]
> I'm sorry for the delayed response. The data I used for replication is accessible at https://doi.org/10.1111/jofi.12883. The file name is jofi12883-sup-0001-ReplicationCode.zip (See the supporting information)

thanks for reply.
